/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gebak_000
 */
public class AccountManagement extends javax.swing.JPanel {

    /**
     * Creates new form AccountManagement
     */
    public AccountManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACCOUNT_MANAGEMENT = new javax.swing.JPanel();
        NEW_USER = new javax.swing.JLabel();
        NEW_USERNAME = new javax.swing.JLabel();
        NEW_PASSWORD_INPUT = new javax.swing.JTextField();
        NEW_PASSWORD = new javax.swing.JLabel();
        NEW_USERNAME_INPUT = new javax.swing.JTextField();
        CHANGE_PASSWORD_TEXT = new javax.swing.JLabel();
        CHANGE_USERNAME_TEXT = new javax.swing.JLabel();
        CHANGE_PASSWORD_INPUT = new javax.swing.JTextField();
        CHANGE_PASSWORD = new javax.swing.JLabel();
        USER = new javax.swing.JComboBox();
        NEW_CONFIRM = new javax.swing.JButton();
        CHANGE_CONFIRM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        NEW_USER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NEW_USER.setText("New User");

        NEW_USERNAME.setText("Username:");

        NEW_PASSWORD_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_PASSWORD_INPUTActionPerformed(evt);
            }
        });

        NEW_PASSWORD.setText("Password:");

        NEW_USERNAME_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_USERNAME_INPUTActionPerformed(evt);
            }
        });

        CHANGE_PASSWORD_TEXT.setText("Password:");

        CHANGE_USERNAME_TEXT.setText("Username:");

        CHANGE_PASSWORD_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGE_PASSWORD_INPUTActionPerformed(evt);
            }
        });

        CHANGE_PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CHANGE_PASSWORD.setText("Change Password");

        USER.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User1", "User2", "User3", "User4" }));
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });

        NEW_CONFIRM.setText("Confirm");
        NEW_CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_CONFIRMActionPerformed(evt);
            }
        });

        CHANGE_CONFIRM.setText("Confirm");
        CHANGE_CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGE_CONFIRMActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Delete user");

        jCheckBox1.setText("check to confirm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "User 1", "User 2", "User 3", "User 4" }));

        jButton1.setText("Confirm");

        jLabel2.setText("Username:");

        jLabel3.setText("Verify:");

        javax.swing.GroupLayout ACCOUNT_MANAGEMENTLayout = new javax.swing.GroupLayout(ACCOUNT_MANAGEMENT);
        ACCOUNT_MANAGEMENT.setLayout(ACCOUNT_MANAGEMENTLayout);
        ACCOUNT_MANAGEMENTLayout.setHorizontalGroup(
            ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(NEW_USER)
                    .addComponent(CHANGE_PASSWORD)
                    .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CHANGE_PASSWORD_TEXT)
                            .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NEW_USERNAME)
                                    .addComponent(NEW_PASSWORD))
                                .addComponent(CHANGE_USERNAME_TEXT, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(NEW_CONFIRM)
                            .addComponent(CHANGE_CONFIRM)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NEW_USERNAME_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(NEW_PASSWORD_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(CHANGE_PASSWORD_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(USER, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        ACCOUNT_MANAGEMENTLayout.setVerticalGroup(
            ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NEW_USER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEW_USERNAME)
                    .addComponent(NEW_USERNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEW_PASSWORD)
                    .addComponent(NEW_PASSWORD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NEW_CONFIRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CHANGE_PASSWORD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHANGE_USERNAME_TEXT)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHANGE_PASSWORD_TEXT)
                    .addComponent(CHANGE_PASSWORD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CHANGE_CONFIRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ACCOUNT_MANAGEMENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(ACCOUNT_MANAGEMENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NEW_PASSWORD_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_PASSWORD_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_PASSWORD_INPUTActionPerformed

    private void NEW_USERNAME_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_USERNAME_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_USERNAME_INPUTActionPerformed

    private void CHANGE_PASSWORD_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGE_PASSWORD_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHANGE_PASSWORD_INPUTActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void NEW_CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_CONFIRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_CONFIRMActionPerformed

    private void CHANGE_CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGE_CONFIRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHANGE_CONFIRMActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACCOUNT_MANAGEMENT;
    private javax.swing.JButton CHANGE_CONFIRM;
    private javax.swing.JLabel CHANGE_PASSWORD;
    private javax.swing.JTextField CHANGE_PASSWORD_INPUT;
    private javax.swing.JLabel CHANGE_PASSWORD_TEXT;
    private javax.swing.JLabel CHANGE_USERNAME_TEXT;
    private javax.swing.JButton NEW_CONFIRM;
    private javax.swing.JLabel NEW_PASSWORD;
    private javax.swing.JTextField NEW_PASSWORD_INPUT;
    private javax.swing.JLabel NEW_USER;
    private javax.swing.JLabel NEW_USERNAME;
    private javax.swing.JTextField NEW_USERNAME_INPUT;
    private javax.swing.JComboBox USER;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
