/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.User;


/**
 *
 * @author gebak_000
 */
public class AccountManagement extends javax.swing.JPanel {
    List<model.User> list = new ArrayList<>();
    String[] usernames;

    /**
     * Creates new form AccountManagement
     */
    public AccountManagement() {
        try {
            list = model.UserDAO.readAll();
        } catch (SQLException ex) {
            Logger.getLogger(AccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        usernames = new String[list.size()];
        int index = 0;
        for (User user : list) {
            usernames[index] = user.getUsername();
            index++;
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACCOUNT_MANAGEMENT = new javax.swing.JPanel();
        NEW_USER = new javax.swing.JLabel();
        NEW_USERNAME = new javax.swing.JLabel();
        NEW_PASSWORD_INPUT = new javax.swing.JTextField();
        NEW_PASSWORD = new javax.swing.JLabel();
        NEW_USERNAME_INPUT = new javax.swing.JTextField();
        CHANGE_PASSWORD_TEXT = new javax.swing.JLabel();
        CHANGE_USERNAME_TEXT = new javax.swing.JLabel();
        CHANGE_PASSWORD_INPUT = new javax.swing.JTextField();
        CHANGE_PASSWORD = new javax.swing.JLabel();
        USER = new javax.swing.JComboBox();
        NEW_CONFIRM = new javax.swing.JButton();
        CHANGE_CONFIRM = new javax.swing.JButton();

        NEW_USER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NEW_USER.setText("New User");

        NEW_USERNAME.setText("Username:");

        NEW_PASSWORD_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_PASSWORD_INPUTActionPerformed(evt);
            }
        });

        NEW_PASSWORD.setText("Password:");

        NEW_USERNAME_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_USERNAME_INPUTActionPerformed(evt);
            }
        });

        CHANGE_PASSWORD_TEXT.setText("Password:");

        CHANGE_USERNAME_TEXT.setText("Username:");

        CHANGE_PASSWORD_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGE_PASSWORD_INPUTActionPerformed(evt);
            }
        });

        CHANGE_PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CHANGE_PASSWORD.setText("Change Password");

        USER.setModel(new javax.swing.DefaultComboBoxModel(usernames));
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });

        NEW_CONFIRM.setText("Confirm");
        NEW_CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEW_CONFIRMActionPerformed(evt);
            }
        });

        CHANGE_CONFIRM.setText("Confirm");
        CHANGE_CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHANGE_CONFIRMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ACCOUNT_MANAGEMENTLayout = new javax.swing.GroupLayout(ACCOUNT_MANAGEMENT);
        ACCOUNT_MANAGEMENT.setLayout(ACCOUNT_MANAGEMENTLayout);
        ACCOUNT_MANAGEMENTLayout.setHorizontalGroup(
            ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NEW_USER)
                    .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CHANGE_PASSWORD_TEXT)
                            .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NEW_USERNAME)
                                    .addComponent(NEW_PASSWORD))
                                .addComponent(CHANGE_USERNAME_TEXT, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(NEW_CONFIRM)
                            .addComponent(CHANGE_CONFIRM))
                        .addGap(18, 18, 18)
                        .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NEW_USERNAME_INPUT)
                            .addComponent(NEW_PASSWORD_INPUT)
                            .addComponent(CHANGE_PASSWORD_INPUT)
                            .addComponent(USER, 0, 100, Short.MAX_VALUE)))
                    .addComponent(CHANGE_PASSWORD))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        ACCOUNT_MANAGEMENTLayout.setVerticalGroup(
            ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ACCOUNT_MANAGEMENTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NEW_USER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEW_USERNAME)
                    .addComponent(NEW_USERNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEW_PASSWORD)
                    .addComponent(NEW_PASSWORD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NEW_CONFIRM)
                .addGap(18, 18, 18)
                .addComponent(CHANGE_PASSWORD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHANGE_USERNAME_TEXT)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ACCOUNT_MANAGEMENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHANGE_PASSWORD_TEXT)
                    .addComponent(CHANGE_PASSWORD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CHANGE_CONFIRM)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ACCOUNT_MANAGEMENT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ACCOUNT_MANAGEMENT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NEW_PASSWORD_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_PASSWORD_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_PASSWORD_INPUTActionPerformed

    private void NEW_USERNAME_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_USERNAME_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NEW_USERNAME_INPUTActionPerformed

    private void CHANGE_PASSWORD_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGE_PASSWORD_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHANGE_PASSWORD_INPUTActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void NEW_CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEW_CONFIRMActionPerformed
        model.User user = new model.User();
        user.setUsername(NEW_USERNAME_INPUT.getText());
        user.setPassword(NEW_PASSWORD_INPUT.getText());
        user.setPrivileges("Admin");
        try {
            model.UserDAO.create(user);
        } catch (SQLException ex) {
            Logger.getLogger(AccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NEW_CONFIRMActionPerformed

    private void CHANGE_CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHANGE_CONFIRMActionPerformed
        String pass = CHANGE_PASSWORD_INPUT.getText();
        try {
            model.User user = model.UserDAO.readByUsername(USER.getSelectedItem().toString());
            user.setPassword(pass);
            model.UserDAO.update(user);
        } catch (SQLException ex) {
            Logger.getLogger(AccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CHANGE_CONFIRMActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ACCOUNT_MANAGEMENT;
    private javax.swing.JButton CHANGE_CONFIRM;
    private javax.swing.JLabel CHANGE_PASSWORD;
    private javax.swing.JTextField CHANGE_PASSWORD_INPUT;
    private javax.swing.JLabel CHANGE_PASSWORD_TEXT;
    private javax.swing.JLabel CHANGE_USERNAME_TEXT;
    private javax.swing.JButton NEW_CONFIRM;
    private javax.swing.JLabel NEW_PASSWORD;
    private javax.swing.JTextField NEW_PASSWORD_INPUT;
    private javax.swing.JLabel NEW_USER;
    private javax.swing.JLabel NEW_USERNAME;
    private javax.swing.JTextField NEW_USERNAME_INPUT;
    private javax.swing.JComboBox USER;
    // End of variables declaration//GEN-END:variables
}
