/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Color;
import java.util.List;
import model.Passenger;
import model.Luggage;
import model.Address;

/**
 *
 * @author Tomas Slaman
 */
public class EditPanel extends javax.swing.JPanel {

    private List<Luggage> connectedLuggages;
    
    /**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
    }
    
    public void fillPassengerInformation(Passenger passenger)
    {
        Address ha = passenger.getHomeaddress();
        Address ta = passenger.getTempaddress();
        this.NAME_INPUT.setText(passenger.getName());
        this.TUSSENVOEGSEL_INPUT.setText(passenger.getInsertion());
        this.SURNAME_INPUT.setText(passenger.getSurname());
        this.DATE_OF_BIRTH_INPUT.setText(passenger.getDob().toString());
        if (passenger.getGender().equals("m"))
            this.MALE_BUTTON.setSelected(true);
        else
            this.FEMALE_BUTTON.setSelected(true);
        this.HOME_PHONE_NUMBER_INPUT.setText(passenger.getHomephone());
        this.MOBILE_PHONE_NUMBER_INPUT.setText(passenger.getMobphone());
        
        this.HOME_COUNTRY_INPUT.setSelectedItem(ha.getCountry());
        this.HOME_CITY_INPUT.setText(ha.getCity());
        this.HOME_STREET_INPUT.setText(ha.getStreetname());
        this.HOME_POSTAL_CODE_INPUT.setText(ha.getZipcode());
        
        this.TEMP_COUNTRY_INPUT.setSelectedItem(ta.getCountry());
        this.TEMP_CITY_INPUT.setText(ta.getCity());
        this.TEMP_STREET_INPUT.setText(ta.getStreetname());
        this.TEMP_POSTAL_CODE_INPUT.setText(ta.getZipcode());
    }
    
    public void populateComboBox(List<Luggage> conLuggages)
    {
        this.connectedLuggages = conLuggages;
        conLuggages = null;
        for (Luggage l : this.connectedLuggages)
            this.CONNECTED_LUGGAGES_CBOX.addItem(l.getLuggageLabel());
        
        this.CONNECTED_LUGGAGES_CBOX.setSelectedIndex(0);
        setLuggageEditability(true);
    }
    
    public void setLuggageEditability(Boolean bool)
    {
        Color c = bool ? Color.WHITE : Color.LIGHT_GRAY;
        this.CONNECTED_LUGGAGES_CBOX.setEnabled(bool);
        this.DESCRIPTION_INPUT1.setEnabled(bool);
        setStorageLocationEditability();
        this.STATUS_COMBOBOX.setEnabled(bool);
        setLuggageColors(c);
    }
    
    public void setLuggageColors(Color c)
    {
        this.CONNECTED_LUGGAGES_CBOX.setBackground(c);
        this.DESCRIPTION_INPUT1.setBackground(c);
        this.STATUS_COMBOBOX.setBackground(c);
    }
    
    public void setPassengerEditability(Boolean bool)
    {
    }
    
    public void setStorageLocationEditability()
    {
        if (STORAGE_LOCATION_INPUT.getSelectedItem().toString().equals("Other")) {
            ANDERS_INPUT.setEnabled(true);
            ANDERS_INPUT.setBackground(Color.WHITE);
        } else if (ANDERS_INPUT.isEditable()) {
            ANDERS_INPUT.setEnabled(false);
            ANDERS_INPUT.setBackground(Color.lightGray);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        NAME_INPUT = new javax.swing.JTextField();
        TUSSENVOEGSEL_INPUT = new javax.swing.JTextField();
        SURNAME_INPUT = new javax.swing.JTextField();
        DATE_OF_BIRTH_INPUT = new javax.swing.JFormattedTextField();
        DD_MM_YYYY = new javax.swing.JLabel();
        FEMALE_BUTTON = new javax.swing.JRadioButton();
        MALE_BUTTON = new javax.swing.JRadioButton();
        HOME_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        MOBILE_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        HOME_COUNTRY_INPUT = new javax.swing.JComboBox();
        HOME_CITY_INPUT = new javax.swing.JTextField();
        HOME_STREET_INPUT = new javax.swing.JTextField();
        HOME_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        TEMP_COUNTRY_INPUT = new javax.swing.JComboBox();
        TEMP_CITY_INPUT = new javax.swing.JTextField();
        TEMP_STREET_INPUT = new javax.swing.JTextField();
        TEMP_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        TEMP_POSTAL_CODE = new javax.swing.JLabel();
        TEMP_STREET = new javax.swing.JLabel();
        TEMP_CITY = new javax.swing.JLabel();
        TEMP_COUNTRY = new javax.swing.JLabel();
        TEMPORARY_ADDRESS_TITLE = new javax.swing.JLabel();
        HOME_POSTAL_CODE = new javax.swing.JLabel();
        HOME_STREET = new javax.swing.JLabel();
        HOME_CITY = new javax.swing.JLabel();
        HOME_COUNTRY = new javax.swing.JLabel();
        HOME_ADDRESS_TITLE = new javax.swing.JLabel();
        MOBILE_PHONE_NUMBER = new javax.swing.JLabel();
        HOME_PHONE_NUMBER = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        DATE_OF_BIRTH = new javax.swing.JLabel();
        SURNAME = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        BASIC_INFORMATION_TITLE = new javax.swing.JLabel();
        CONNECTED_LUGGAGES_CBOX = new javax.swing.JComboBox();
        DESCRIPTION = new javax.swing.JLabel();
        DESCRIPTION_INPUT_FRAME = new javax.swing.JScrollPane();
        DESCRIPTION_INPUT1 = new javax.swing.JTextArea();
        STORAGE_LOCATION_INPUT = new javax.swing.JComboBox();
        ANDERS_INPUT_FRAME = new javax.swing.JScrollPane();
        ANDERS_INPUT = new javax.swing.JTextArea();
        STORAGE_LOCATION = new javax.swing.JLabel();
        ANDERS = new javax.swing.JLabel();
        LUGGAGE_INFORMATION_LABEL = new javax.swing.JLabel();
        CONNECTED_LUGGAGES_LABEL = new javax.swing.JLabel();
        LUGGAGE_NOT_LINKED_LABEL = new javax.swing.JLabel();
        LUGGAGE_NOT_LINKED_COPY = new javax.swing.JLabel();
        SAVE_BUTTON = new javax.swing.JButton();
        CANCEL_BUTTON = new javax.swing.JButton();
        LUGGAGE_NOT_LINKED_COPY2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        STATUS_COMBOBOX = new javax.swing.JComboBox();

        setName(""); // NOI18N

        TUSSENVOEGSEL_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUSSENVOEGSEL_INPUTActionPerformed(evt);
            }
        });

        DATE_OF_BIRTH_INPUT.setColumns(3);

        DD_MM_YYYY.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        DD_MM_YYYY.setText("(YYYY-MM-DD)");

        FEMALE_BUTTON.setText("Female");
        FEMALE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEMALE_BUTTONActionPerformed(evt);
            }
        });

        MALE_BUTTON.setSelected(true);
        MALE_BUTTON.setText("Male");
        MALE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALE_BUTTONActionPerformed(evt);
            }
        });

        MOBILE_PHONE_NUMBER_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILE_PHONE_NUMBER_INPUTActionPerformed(evt);
            }
        });

        HOME_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        TEMP_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        TEMP_POSTAL_CODE.setText("Postal Code");

        TEMP_STREET.setText("Street");

        TEMP_CITY.setText("City");

        TEMP_COUNTRY.setText("Country");

        TEMPORARY_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TEMPORARY_ADDRESS_TITLE.setText("Temporary Address");

        HOME_POSTAL_CODE.setText("Postal Code");

        HOME_STREET.setText("Street");

        HOME_CITY.setText("City");

        HOME_COUNTRY.setText("Country");

        HOME_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HOME_ADDRESS_TITLE.setText("Home Address");

        MOBILE_PHONE_NUMBER.setText("Mobile Phone Number");
        MOBILE_PHONE_NUMBER.setAlignmentY(0.0F);

        HOME_PHONE_NUMBER.setText("Home Phone Number");

        GENDER.setText("Gender");

        DATE_OF_BIRTH.setText("Date of Birth");

        SURNAME.setText("Surname");

        NAME.setText("Name");

        BASIC_INFORMATION_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BASIC_INFORMATION_TITLE.setText("Basic Information");

        CONNECTED_LUGGAGES_CBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONNECTED_LUGGAGES_CBOXActionPerformed(evt);
            }
        });

        DESCRIPTION.setText("Description");

        DESCRIPTION_INPUT1.setColumns(20);
        DESCRIPTION_INPUT1.setRows(5);
        DESCRIPTION_INPUT_FRAME.setViewportView(DESCRIPTION_INPUT1);

        STORAGE_LOCATION_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Opslag A", "Opslag B", "Opslag C", "Other" }));
        STORAGE_LOCATION_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STORAGE_LOCATION_INPUTActionPerformed(evt);
            }
        });

        ANDERS_INPUT.setColumns(20);
        ANDERS_INPUT.setRows(5);
        ANDERS_INPUT.setText("Vul hier zo specifiek mogelijk de\ngegevens in van de opslagplaats.");
        ANDERS_INPUT_FRAME.setViewportView(ANDERS_INPUT);

        STORAGE_LOCATION.setText("Storage Location");

        ANDERS.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        ANDERS.setText("Other");

        LUGGAGE_INFORMATION_LABEL.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LUGGAGE_INFORMATION_LABEL.setText("Luggage Information");

        CONNECTED_LUGGAGES_LABEL.setText("Connected Luggages");

        LUGGAGE_NOT_LINKED_LABEL.setForeground(new java.awt.Color(204, 0, 0));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LUGGAGE_NOT_LINKED_LABEL, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), LUGGAGE_NOT_LINKED_COPY, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LUGGAGE_NOT_LINKED_LABEL, org.jdesktop.beansbinding.ELProperty.create("${text}"), LUGGAGE_NOT_LINKED_COPY, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        SAVE_BUTTON.setText("Save");

        CANCEL_BUTTON.setText("Cancel");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LUGGAGE_NOT_LINKED_LABEL, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), LUGGAGE_NOT_LINKED_COPY2, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, LUGGAGE_NOT_LINKED_LABEL, org.jdesktop.beansbinding.ELProperty.create("${text}"), LUGGAGE_NOT_LINKED_COPY2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Status");

        STATUS_COMBOBOX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Missing", "Found", "Returned", "Destroyed" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HOME_ADDRESS_TITLE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BASIC_INFORMATION_TITLE)
                                .addGap(18, 18, 18)
                                .addComponent(LUGGAGE_NOT_LINKED_LABEL))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HOME_CITY)
                                            .addComponent(HOME_COUNTRY)
                                            .addComponent(HOME_STREET)
                                            .addComponent(HOME_POSTAL_CODE))
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(HOME_STREET_INPUT, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(HOME_CITY_INPUT, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(HOME_COUNTRY_INPUT, javax.swing.GroupLayout.Alignment.TRAILING, 0, 200, Short.MAX_VALUE)
                                            .addComponent(HOME_POSTAL_CODE_INPUT)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SURNAME)
                                            .addComponent(DATE_OF_BIRTH)
                                            .addComponent(GENDER)
                                            .addComponent(NAME)
                                            .addComponent(HOME_PHONE_NUMBER)
                                            .addComponent(MOBILE_PHONE_NUMBER))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(DATE_OF_BIRTH_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(DD_MM_YYYY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(SURNAME_INPUT))
                                                    .addComponent(NAME_INPUT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(MALE_BUTTON)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(FEMALE_BUTTON)
                                                    .addGap(75, 75, 75)))
                                            .addComponent(HOME_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MOBILE_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(LUGGAGE_NOT_LINKED_COPY)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TEMP_CITY)
                                                .addComponent(TEMP_COUNTRY)
                                                .addComponent(TEMP_STREET)
                                                .addComponent(TEMP_POSTAL_CODE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(55, 55, 55)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(TEMP_COUNTRY_INPUT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TEMP_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(56, 56, 56)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TEMP_STREET_INPUT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TEMP_POSTAL_CODE_INPUT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TEMPORARY_ADDRESS_TITLE)
                                            .addGap(18, 18, 18)
                                            .addComponent(LUGGAGE_NOT_LINKED_COPY2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LUGGAGE_INFORMATION_LABEL)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(CONNECTED_LUGGAGES_LABEL)
                                            .addGap(18, 18, 18)
                                            .addComponent(CONNECTED_LUGGAGES_CBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(STORAGE_LOCATION)
                                    .addComponent(DESCRIPTION)
                                    .addComponent(ANDERS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(STATUS_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DESCRIPTION_INPUT_FRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(STORAGE_LOCATION_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ANDERS_INPUT_FRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CANCEL_BUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAVE_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TEMPORARY_ADDRESS_TITLE)
                        .addComponent(BASIC_INFORMATION_TITLE))
                    .addComponent(LUGGAGE_NOT_LINKED_LABEL)
                    .addComponent(LUGGAGE_NOT_LINKED_COPY2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(NAME))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(NAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SURNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SURNAME))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DATE_OF_BIRTH_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DD_MM_YYYY)
                                    .addComponent(DATE_OF_BIRTH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MALE_BUTTON)
                                    .addComponent(FEMALE_BUTTON)
                                    .addComponent(GENDER))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HOME_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOME_PHONE_NUMBER))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MOBILE_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MOBILE_PHONE_NUMBER))))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HOME_ADDRESS_TITLE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HOME_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HOME_COUNTRY)))
                            .addComponent(LUGGAGE_NOT_LINKED_COPY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HOME_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HOME_CITY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HOME_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HOME_STREET))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HOME_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HOME_POSTAL_CODE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEMP_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEMP_COUNTRY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEMP_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEMP_CITY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEMP_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEMP_STREET))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEMP_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TEMP_POSTAL_CODE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LUGGAGE_INFORMATION_LABEL)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CONNECTED_LUGGAGES_CBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CONNECTED_LUGGAGES_LABEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESCRIPTION)
                            .addComponent(DESCRIPTION_INPUT_FRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(STORAGE_LOCATION_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(STORAGE_LOCATION))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ANDERS)
                            .addComponent(ANDERS_INPUT_FRAME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(STATUS_COMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE_BUTTON)
                    .addComponent(CANCEL_BUTTON))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void STORAGE_LOCATION_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STORAGE_LOCATION_INPUTActionPerformed
        setStorageLocationEditability();
    }//GEN-LAST:event_STORAGE_LOCATION_INPUTActionPerformed

    private void MOBILE_PHONE_NUMBER_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILE_PHONE_NUMBER_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILE_PHONE_NUMBER_INPUTActionPerformed

    private void MALE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALE_BUTTONActionPerformed
        if (FEMALE_BUTTON.isSelected()) {
            FEMALE_BUTTON.setSelected(false);
        } else {
            FEMALE_BUTTON.setSelected(true);
        }
    }//GEN-LAST:event_MALE_BUTTONActionPerformed

    private void FEMALE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEMALE_BUTTONActionPerformed
        if (MALE_BUTTON.isSelected()) {
            MALE_BUTTON.setSelected(false);
        } else {
            MALE_BUTTON.setSelected(true);
        }
    }//GEN-LAST:event_FEMALE_BUTTONActionPerformed

    private void TUSSENVOEGSEL_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUSSENVOEGSEL_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TUSSENVOEGSEL_INPUTActionPerformed

    private void CONNECTED_LUGGAGES_CBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONNECTED_LUGGAGES_CBOXActionPerformed
        Luggage selectedLuggage = this.connectedLuggages.get(this.CONNECTED_LUGGAGES_CBOX.getSelectedIndex());
        
        this.DESCRIPTION_INPUT1.setText(selectedLuggage.getDescription());
        this.STORAGE_LOCATION_INPUT.setSelectedItem(selectedLuggage.getStoragelocation());
        this.ANDERS_INPUT.setText(selectedLuggage.getDifferentLocation());
        this.STATUS_COMBOBOX.setSelectedItem(selectedLuggage.getLuggagestatus());
        
    }//GEN-LAST:event_CONNECTED_LUGGAGES_CBOXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANDERS;
    private javax.swing.JTextArea ANDERS_INPUT;
    private javax.swing.JScrollPane ANDERS_INPUT_FRAME;
    private javax.swing.JLabel BASIC_INFORMATION_TITLE;
    private javax.swing.JButton CANCEL_BUTTON;
    private javax.swing.JComboBox CONNECTED_LUGGAGES_CBOX;
    private javax.swing.JLabel CONNECTED_LUGGAGES_LABEL;
    private javax.swing.JLabel DATE_OF_BIRTH;
    private javax.swing.JFormattedTextField DATE_OF_BIRTH_INPUT;
    private javax.swing.JLabel DD_MM_YYYY;
    private javax.swing.JLabel DESCRIPTION;
    private javax.swing.JTextArea DESCRIPTION_INPUT1;
    private javax.swing.JScrollPane DESCRIPTION_INPUT_FRAME;
    private javax.swing.JRadioButton FEMALE_BUTTON;
    private javax.swing.JLabel GENDER;
    private javax.swing.JLabel HOME_ADDRESS_TITLE;
    private javax.swing.JLabel HOME_CITY;
    private javax.swing.JTextField HOME_CITY_INPUT;
    private javax.swing.JLabel HOME_COUNTRY;
    private javax.swing.JComboBox HOME_COUNTRY_INPUT;
    private javax.swing.JLabel HOME_PHONE_NUMBER;
    private javax.swing.JTextField HOME_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel HOME_POSTAL_CODE;
    private javax.swing.JTextField HOME_POSTAL_CODE_INPUT;
    private javax.swing.JLabel HOME_STREET;
    private javax.swing.JTextField HOME_STREET_INPUT;
    private javax.swing.JLabel LUGGAGE_INFORMATION_LABEL;
    private javax.swing.JLabel LUGGAGE_NOT_LINKED_COPY;
    private javax.swing.JLabel LUGGAGE_NOT_LINKED_COPY2;
    private javax.swing.JLabel LUGGAGE_NOT_LINKED_LABEL;
    private javax.swing.JRadioButton MALE_BUTTON;
    private javax.swing.JLabel MOBILE_PHONE_NUMBER;
    private javax.swing.JTextField MOBILE_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField NAME_INPUT;
    private javax.swing.JButton SAVE_BUTTON;
    private javax.swing.JComboBox STATUS_COMBOBOX;
    private javax.swing.JLabel STORAGE_LOCATION;
    private javax.swing.JComboBox STORAGE_LOCATION_INPUT;
    private javax.swing.JLabel SURNAME;
    private javax.swing.JTextField SURNAME_INPUT;
    private javax.swing.JLabel TEMPORARY_ADDRESS_TITLE;
    private javax.swing.JLabel TEMP_CITY;
    private javax.swing.JTextField TEMP_CITY_INPUT;
    private javax.swing.JLabel TEMP_COUNTRY;
    private javax.swing.JComboBox TEMP_COUNTRY_INPUT;
    private javax.swing.JLabel TEMP_POSTAL_CODE;
    private javax.swing.JTextField TEMP_POSTAL_CODE_INPUT;
    private javax.swing.JLabel TEMP_STREET;
    private javax.swing.JTextField TEMP_STREET_INPUT;
    private javax.swing.JTextField TUSSENVOEGSEL_INPUT;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
