/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gebak_000
 */
import main.LuggageTrackerTool2;

public class LTTLogin extends javax.swing.JPanel {

    /**
     * Creates new form LTTLogin
     */
    public LTTLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INSTRUCTIONS_LABEL = new javax.swing.JLabel();
        LOGIN_BUTTON = new javax.swing.JButton();
        CANCEL_BUTTON = new javax.swing.JButton();
        USERNAME_LABEL = new javax.swing.JLabel();
        PASSWORD_LABEL = new javax.swing.JLabel();
        USERNAME_INPUT = new javax.swing.JTextField();
        PASSWORD_INPUT = new javax.swing.JPasswordField();
        TITLE_LABEL = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        INSTRUCTIONS_LABEL.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        INSTRUCTIONS_LABEL.setText("Please enter your username and password.");

        LOGIN_BUTTON.setText("Login");
        LOGIN_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGIN_BUTTONActionPerformed(evt);
            }
        });

        CANCEL_BUTTON.setText("Cancel");
        CANCEL_BUTTON.setMaximumSize(new java.awt.Dimension(63, 25));
        CANCEL_BUTTON.setMinimumSize(new java.awt.Dimension(63, 25));
        CANCEL_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCEL_BUTTONActionPerformed(evt);
            }
        });

        USERNAME_LABEL.setText("Username:");

        PASSWORD_LABEL.setText("Password:");

        USERNAME_INPUT.setText("admin");
        USERNAME_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAME_INPUTActionPerformed(evt);
            }
        });

        PASSWORD_INPUT.setText("admin");

        TITLE_LABEL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TITLE_LABEL.setText("LUGGAGETRACKERTOOL v1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(106, Short.MAX_VALUE)
                        .addComponent(TITLE_LABEL))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(INSTRUCTIONS_LABEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CANCEL_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PASSWORD_LABEL)
                                    .addComponent(USERNAME_LABEL))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(USERNAME_INPUT)
                                    .addComponent(PASSWORD_INPUT))))))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TITLE_LABEL)
                .addGap(32, 32, 32)
                .addComponent(INSTRUCTIONS_LABEL)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USERNAME_LABEL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PASSWORD_LABEL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CANCEL_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(LOGIN_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAME_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAME_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAME_INPUTActionPerformed

    private void LOGIN_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGIN_BUTTONActionPerformed
        if (main.LuggageTrackerTool2.getInstance().authenticate(USERNAME_INPUT.getText(), PASSWORD_INPUT.getPassword())) {
            main.LuggageTrackerTool2.getInstance().startup();
        } else {
            
            INSTRUCTIONS_LABEL.setText("Incorrect credentials. Please try again.");
        }
    }//GEN-LAST:event_LOGIN_BUTTONActionPerformed

    private void CANCEL_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCEL_BUTTONActionPerformed
        LuggageTrackerTool2.getInstance().exit();
    }//GEN-LAST:event_CANCEL_BUTTONActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL_BUTTON;
    private javax.swing.JLabel INSTRUCTIONS_LABEL;
    private javax.swing.JButton LOGIN_BUTTON;
    private javax.swing.JPasswordField PASSWORD_INPUT;
    private javax.swing.JLabel PASSWORD_LABEL;
    private javax.swing.JLabel TITLE_LABEL;
    private javax.swing.JTextField USERNAME_INPUT;
    private javax.swing.JLabel USERNAME_LABEL;
    // End of variables declaration//GEN-END:variables
}
