/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;

/**
 *
 * @author gebak_000
 */
public class Luggage extends javax.swing.JPanel {

    private java.util.List<model.Luggage> luggageList = new java.util.ArrayList<>();

    /**
     * Creates new form Luggage
     */
    public Luggage() {
        initComponents();
        addLuggageItemsToTable();
    }

    private void refreshLuggageList() {
        try {
            luggageList = model.LuggageDAO.readAll();
        } catch (SQLException ex) {
            System.err.println("Error getting luggage list: " + ex.getMessage());
        }
    }

    public void addLuggageItemsToTable() {
        
        refreshLuggageList();
        
        for (model.Luggage luggage : luggageList) {
            addLuggageToTable(luggage);
        }
    }

    private void addRow(Object[] row) {
        ((javax.swing.table.DefaultTableModel) LUGGAGE_TABLE.getModel()).addRow(row);
    }

    public void addLuggageToTable(model.Luggage luggage) {
        Object[] newRow = new Object[4];
        newRow[0] = luggage.getLuggageid();
        newRow[1] = luggage.getDescription();
        newRow[2] = luggage.getStoragelocation();
        newRow[3] = luggage.getPassengerid();
        addRow(newRow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LUGGAGE_TABLE = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        CONNECT_TO_CUSTOMER_BUTTON = new javax.swing.JButton();
        EDIT_BUTTON = new javax.swing.JButton();
        DELETE_BUTTON = new javax.swing.JButton();

        LUGGAGE_TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Luggage ID", "Luggage Description", "Storage Location", "PassengerID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LUGGAGE_TABLE.setName("Luggage"); // NOI18N
        jScrollPane1.setViewportView(LUGGAGE_TABLE);
        if (LUGGAGE_TABLE.getColumnModel().getColumnCount() > 0) {
            LUGGAGE_TABLE.getColumnModel().getColumn(0).setResizable(false);
            LUGGAGE_TABLE.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        CONNECT_TO_CUSTOMER_BUTTON.setText("Connect to Customer");
        jToolBar1.add(CONNECT_TO_CUSTOMER_BUTTON);

        EDIT_BUTTON.setText("Edit");
        jToolBar1.add(EDIT_BUTTON);

        DELETE_BUTTON.setText("Delete");
        jToolBar1.add(DELETE_BUTTON);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONNECT_TO_CUSTOMER_BUTTON;
    private javax.swing.JButton DELETE_BUTTON;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JTable LUGGAGE_TABLE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
