package view;

import javax.swing.JPanel;

/**
 *
 * @author reintjehard
 */
public class MainMenu extends JPanel {
    private JPanel passengerTab, luggageTab, accountTab;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        passengerTab = new view.Passenger();
        luggageTab = new view.Luggage();
        accountTab = new view.AccountManagement();
        
        initComponents();
        
        jTabbedPane.addTab("Passenger", passengerTab);
        jTabbedPane.addTab("Luggage", luggageTab);
        jTabbedPane.addTab("Account Management", accountTab);
    }

    public view.Passenger getPassengerTab() {
        return (Passenger) passengerTab;
    }

    public view.Luggage getLuggageTab() {
        return (Luggage) luggageTab;
    }

    public JPanel getAccountTab() {
        return accountTab;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Main menu"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
