package view;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author reintjehard
 */
public class MainMenu extends JPanel {

    private JPanel passengerTab, luggageTab, accountTab, managementTab;
    private view.InformationPanel informationPanel;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        String rights = main.LuggageTrackerTool2.getInstance().getCurrentUser().getPrivileges();

        switch (rights) {
            case "Manager":
                addManagerTabs();
                break;
            case "Admin":
                addAllTabs();
                break;
            case "Account Manager":
                addAccountManagerTabs();
                break;
            case "Service Employee":
                addServiceEmployeeTabs();
                break;

        }
        
    }

    private void addManagerTabs() {
        managementTab = new view.Management();
        jTabbedPane.add("Manager Pane", managementTab);
    }

    private void addAllTabs() {
        managementTab = new view.Management();
        passengerTab = new view.Passenger();
        luggageTab = new view.Luggage();
        accountTab = new view.AccountManagement();
        informationPanel = new view.InformationPanel();
        informationPanel.setVisible(true);
        add(informationPanel, BorderLayout.PAGE_END);
        jTabbedPane.addTab("Passenger", passengerTab);
        jTabbedPane.addTab("Luggage", luggageTab);
        jTabbedPane.addTab("Account Management", accountTab);
        jTabbedPane.add("Manager Pane", managementTab);
    }

    private void addServiceEmployeeTabs() {
        passengerTab = new view.Passenger();
        luggageTab = new view.Luggage();
        
        jTabbedPane.addTab("Passenger", passengerTab);
        jTabbedPane.addTab("Luggage", luggageTab);
    }

    private void addAccountManagerTabs() {
        passengerTab = new view.Passenger();
        luggageTab = new view.Luggage();
        accountTab = new view.AccountManagement();
        
        jTabbedPane.addTab("Passenger", passengerTab);
        jTabbedPane.addTab("Luggage", luggageTab);
        jTabbedPane.addTab("Account Management", accountTab);
    }

    public view.Passenger getPassengerTab() {
        return (Passenger) passengerTab;
    }

    public view.Luggage getLuggageTab() {
        return (Luggage) luggageTab;
    }

    public JPanel getAccountTab() {
        return accountTab;
    }

    public JTabbedPane getjTabbedPane() {
        return jTabbedPane;
    }

    public InformationPanel getInformationPanel() {
        return informationPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Main menu"));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane.setPreferredSize(new java.awt.Dimension(400, 650));
        jTabbedPane.setRequestFocusEnabled(false);
        add(jTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables

}
