/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JPanel;
import main.CustomException;
import utility.PDFGenerator;
import view.ManagerGraph;

/**
 *
 * @author gebak_000
 */
public class ManagerMenu extends JPanel {

    /**
     * Creates new form ManagerMenu
     */
    public ManagerMenu() {
        initComponents();
        dateFormat1();
        dateFormat2();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLE = new javax.swing.JLabel();
        FIRST_DATE_LABEL = new javax.swing.JLabel();
        LAST_DATE_LABEL = new javax.swing.JLabel();
        FIRST_DATE_INPUT = new javax.swing.JFormattedTextField();
        LAST_DATE_INPUT = new javax.swing.JFormattedTextField();
        FIRST_DATE_FORMAT = new javax.swing.JLabel();
        LAST_DATE_FORMAT = new javax.swing.JLabel();
        CONFIRM_BUTTON = new javax.swing.JButton();

        TITLE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TITLE.setText("Graph Settings");

        FIRST_DATE_LABEL.setText("Firste date:");

        LAST_DATE_LABEL.setText("Last date:");

        FIRST_DATE_FORMAT.setText("(YYYY-MM-DD)");

        LAST_DATE_FORMAT.setText("(YYYY-MM-DD)");

        CONFIRM_BUTTON.setText("Confirm");
        CONFIRM_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRM_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TITLE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FIRST_DATE_LABEL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FIRST_DATE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LAST_DATE_LABEL)
                                .addGap(18, 18, 18)
                                .addComponent(LAST_DATE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FIRST_DATE_FORMAT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LAST_DATE_FORMAT, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CONFIRM_BUTTON)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITLE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIRST_DATE_LABEL)
                    .addComponent(FIRST_DATE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIRST_DATE_FORMAT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAST_DATE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LAST_DATE_FORMAT)
                    .addComponent(LAST_DATE_LABEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(CONFIRM_BUTTON)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIRM_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRM_BUTTONActionPerformed
          main.LuggageTrackerTool2.getInstance().getMainMenu().getManagerBarChart().refresh(getFIRST_DATE_INPUT().getText(), getLAST_DATE_INPUT().getText());
    }//GEN-LAST:event_CONFIRM_BUTTONActionPerformed
    
    public JFormattedTextField getFIRST_DATE_INPUT() {
        return FIRST_DATE_INPUT;
    }
    
    public void dateFormat1 (){
        main.LuggageTrackerTool2.getInstance().createJFTFMask(getFIRST_DATE_INPUT(), "yyyy-MM-dd", "####-##-##");
    }
    
    public JFormattedTextField getLAST_DATE_INPUT() {
        return LAST_DATE_INPUT;
    }

    public void dateFormat2 () {
        main.LuggageTrackerTool2.getInstance().createJFTFMask(getLAST_DATE_INPUT(), "yyyy-MM-dd", "####-##-##");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONFIRM_BUTTON;
    private javax.swing.JLabel FIRST_DATE_FORMAT;
    private javax.swing.JFormattedTextField FIRST_DATE_INPUT;
    private javax.swing.JLabel FIRST_DATE_LABEL;
    private javax.swing.JLabel LAST_DATE_FORMAT;
    private javax.swing.JFormattedTextField LAST_DATE_INPUT;
    private javax.swing.JLabel LAST_DATE_LABEL;
    private javax.swing.JLabel TITLE;
    // End of variables declaration//GEN-END:variables
}
