/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Haris
 */
public class RegistrationPassenger extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPassenger
     */
    public RegistrationPassenger() {
        initComponents();
    }

    public model.Passenger createPassenger() {
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        model.Passenger tempPassenger = new model.Passenger();

        tempPassenger.setName(NAME_INPUT.getText());
        tempPassenger.setInsertion(SURNAME_TUSSENVOEGSEL_INPUT.getText());
        tempPassenger.setSurname(SURNAME_INPUT.getText());
        try {
            tempPassenger.setDob(df.parse(DATE_OF_BIRTH_INPUT.getText()));
        } catch (ParseException e) {
            System.out.println(e);
        }
        tempPassenger.setGender(MALE_BUTTON.isSelected() ? "m" : "f");

        tempPassenger.setHomephone(HOME_PHONE_NUMBER_INPUT.getText());
        tempPassenger.setMobphone(MOBILE_PHONE_NUMBER_INPUT.getText());

        clearFields();
        return tempPassenger;
    }

    public model.Address createHomeAddressFromForms() {
        model.Address address = new model.Address();
        address.setCity(HOME_CITY_INPUT.getText());
        address.setCountry(HOME_COUNTRY_INPUT.getSelectedItem().toString());
        address.setStreetname(HOME_STREET_INPUT.getText());
        address.setZipcode(HOME_POSTAL_CODE_INPUT.getText());
        return address;
    }

    public model.Address createTempAddressFromForms() {
        model.Address address = new model.Address();
        address.setCity(TEMP_CITY_INPUT.getText());
        address.setCountry(TEMP_COUNTRY_INPUT.getSelectedItem().toString());
        address.setStreetname(TEMP_STREET_INPUT.getText());
        address.setZipcode(TEMP_POSTAL_CODE_INPUT.getText());
        return address;
    }

    public void clearFields() {
        SURNAME_INPUT.setText("");
        SURNAME_TUSSENVOEGSEL_INPUT.setText("");
        NAME_INPUT.setText("");
        DATE_OF_BIRTH_INPUT.setText("");
        MALE_BUTTON.setSelected(true);
        FEMALE_BUTTON.setSelected(false);
        HOME_PHONE_NUMBER_INPUT.setText("");
        MOBILE_PHONE_NUMBER_INPUT.setText("");

        HOME_CITY_INPUT.setText("");
        HOME_COUNTRY_INPUT.setSelectedIndex(1);
        HOME_STREET_INPUT.setText("");
        HOME_POSTAL_CODE_INPUT.setText("");

        TEMP_CITY_INPUT.setText("");
        TEMP_COUNTRY_INPUT.setSelectedIndex(1);
        TEMP_STREET_INPUT.setText("");
        TEMP_POSTAL_CODE_INPUT.setText("");

    }

    /**
     * 
     * @return Can be accessed from LTT2 class .sideBar.getPassengerControl().getDayOfBirthControl();
     */
    public javax.swing.JFormattedTextField getDateOfBirthControl() {
        return this.DATE_OF_BIRTH_INPUT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        BASIC_INFORMATION_TITLE = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        NAME_INPUT = new javax.swing.JTextField();
        SURNAME = new javax.swing.JLabel();
        SURNAME_TUSSENVOEGSEL_INPUT = new javax.swing.JTextField();
        SURNAME_INPUT = new javax.swing.JTextField();
        DATE_OF_BIRTH = new javax.swing.JLabel();
        DD_MM_YYYY = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        MALE_BUTTON = new javax.swing.JRadioButton();
        FEMALE_BUTTON = new javax.swing.JRadioButton();
        HOME_PHONE_NUMBER = new javax.swing.JLabel();
        HOME_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        MOBILE_PHONE_NUMBER = new javax.swing.JLabel();
        MOBILE_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        HOME_ADDRESS_TITLE = new javax.swing.JLabel();
        HOME_COUNTRY = new javax.swing.JLabel();
        HOME_COUNTRY_INPUT = new javax.swing.JComboBox();
        HOME_CITY = new javax.swing.JLabel();
        HOME_CITY_INPUT = new javax.swing.JTextField();
        HOME_STREET = new javax.swing.JLabel();
        HOME_STREET_INPUT = new javax.swing.JTextField();
        HOME_POSTAL_CODE = new javax.swing.JLabel();
        HOME_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        TEMPORARY_ADDRESS_TITLE = new javax.swing.JLabel();
        TEMP_COUNTRY = new javax.swing.JLabel();
        TEMP_COUNTRY_INPUT = new javax.swing.JComboBox();
        TEMP_CITY = new javax.swing.JLabel();
        TEMP_CITY_INPUT = new javax.swing.JTextField();
        TEMP_STREET = new javax.swing.JLabel();
        TEMP_STREET_INPUT = new javax.swing.JTextField();
        TEMP_POSTAL_CODE = new javax.swing.JLabel();
        TEMP_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        ADDITIONAL_OPTIONS_TITLE = new javax.swing.JLabel();
        PRINT_ON_REGISTER = new javax.swing.JCheckBox();
        PAIR_PASSENGER_LUGGAGE = new javax.swing.JCheckBox();
        PRINT = new javax.swing.JButton();
        REGISTER = new javax.swing.JButton();
        DATE_OF_BIRTH_INPUT = new javax.swing.JFormattedTextField();

        jToggleButton1.setText("jToggleButton1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Register Passenger"));

        BASIC_INFORMATION_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BASIC_INFORMATION_TITLE.setText("Basic Information");

        NAME.setText("Name");

        SURNAME.setText("Surname");

        SURNAME_TUSSENVOEGSEL_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SURNAME_TUSSENVOEGSEL_INPUTActionPerformed(evt);
            }
        });

        DATE_OF_BIRTH.setText("Date of Birth");

        DD_MM_YYYY.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        DD_MM_YYYY.setText("(YYYYMMDD)");

        GENDER.setText("Gender");

        MALE_BUTTON.setText("Male");
        MALE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALE_BUTTONActionPerformed(evt);
            }
        });

        FEMALE_BUTTON.setText("Female");

        HOME_PHONE_NUMBER.setText("Home Phone Number");

        MOBILE_PHONE_NUMBER.setText("Mobile Phone Number");

        HOME_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HOME_ADDRESS_TITLE.setText("Home Address");

        HOME_COUNTRY.setText("Country");

        HOME_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        HOME_CITY.setText("City");

        HOME_STREET.setText("Street");

        HOME_POSTAL_CODE.setText("Postal Code");

        TEMPORARY_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TEMPORARY_ADDRESS_TITLE.setText("Temporary Address");

        TEMP_COUNTRY.setText("Country");

        TEMP_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        TEMP_CITY.setText("City");

        TEMP_STREET.setText("Street");

        TEMP_POSTAL_CODE.setText("Postal Code");

        ADDITIONAL_OPTIONS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ADDITIONAL_OPTIONS_TITLE.setText("Additional Options");

        PRINT_ON_REGISTER.setSelected(true);
        PRINT_ON_REGISTER.setText("Print on register");

        PAIR_PASSENGER_LUGGAGE.setSelected(true);
        PAIR_PASSENGER_LUGGAGE.setText("Pair passenger with luggage");

        PRINT.setText("Print");

        REGISTER.setText("Submit");
        REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERActionPerformed(evt);
            }
        });

        DATE_OF_BIRTH_INPUT.setColumns(3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TEMPORARY_ADDRESS_TITLE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NAME)
                                            .addComponent(SURNAME)
                                            .addComponent(DATE_OF_BIRTH)
                                            .addComponent(GENDER)
                                            .addComponent(TEMP_CITY)
                                            .addComponent(TEMP_COUNTRY)
                                            .addComponent(TEMP_STREET)
                                            .addComponent(TEMP_POSTAL_CODE)
                                            .addComponent(HOME_PHONE_NUMBER)
                                            .addComponent(MOBILE_PHONE_NUMBER)
                                            .addComponent(PRINT_ON_REGISTER)
                                            .addComponent(PRINT)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HOME_CITY)
                                            .addComponent(HOME_COUNTRY)
                                            .addComponent(HOME_STREET)
                                            .addComponent(HOME_POSTAL_CODE))))
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PAIR_PASSENGER_LUGGAGE)
                            .addComponent(REGISTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MALE_BUTTON)
                                .addGap(18, 18, 18)
                                .addComponent(FEMALE_BUTTON))))
                    .addComponent(ADDITIONAL_OPTIONS_TITLE)
                    .addComponent(BASIC_INFORMATION_TITLE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HOME_ADDRESS_TITLE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DATE_OF_BIRTH_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DD_MM_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NAME_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SURNAME_TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SURNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TEMP_POSTAL_CODE_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEMP_STREET_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TEMP_CITY_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HOME_POSTAL_CODE_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HOME_STREET_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HOME_CITY_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HOME_COUNTRY_INPUT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HOME_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MOBILE_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(TEMP_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BASIC_INFORMATION_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAME)
                            .addComponent(NAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SURNAME)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SURNAME_TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SURNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE_OF_BIRTH)
                    .addComponent(DD_MM_YYYY)
                    .addComponent(DATE_OF_BIRTH_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GENDER)
                    .addComponent(MALE_BUTTON)
                    .addComponent(FEMALE_BUTTON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_PHONE_NUMBER)
                    .addComponent(HOME_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOBILE_PHONE_NUMBER)
                    .addComponent(MOBILE_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HOME_ADDRESS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_COUNTRY)
                    .addComponent(HOME_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_CITY)
                    .addComponent(HOME_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_STREET)
                    .addComponent(HOME_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HOME_POSTAL_CODE)
                    .addComponent(HOME_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TEMPORARY_ADDRESS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_COUNTRY)
                    .addComponent(TEMP_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_CITY)
                    .addComponent(TEMP_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_STREET)
                    .addComponent(TEMP_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEMP_POSTAL_CODE)
                    .addComponent(TEMP_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADDITIONAL_OPTIONS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRINT_ON_REGISTER)
                    .addComponent(PAIR_PASSENGER_LUGGAGE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRINT)
                    .addComponent(REGISTER))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MALE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALE_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MALE_BUTTONActionPerformed

    private void SURNAME_TUSSENVOEGSEL_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SURNAME_TUSSENVOEGSEL_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SURNAME_TUSSENVOEGSEL_INPUTActionPerformed

    private void REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERActionPerformed
        try {
            model.Passenger passenger = createPassenger();
            model.Address homeAddress = createHomeAddressFromForms();
            model.Address tempAddress = createTempAddressFromForms();
            homeAddress.setAddressid(1);
            tempAddress.setAddressid(2);
            passenger.setHomeaddress(homeAddress);
            passenger.setTempaddress(tempAddress);
            model.AddressDAO.create(homeAddress);
            model.AddressDAO.create(tempAddress);

            model.PassengerDAO.create(passenger);
            main.LuggageTrackerTool2.getInstance().getMainMenu().getPassengerTab().addPassengerToTable(passenger);
        } catch (SQLException ex) {
            System.err.println("Failed to create passenger.");
            System.err.println("Message: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_REGISTERActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDITIONAL_OPTIONS_TITLE;
    private javax.swing.JLabel BASIC_INFORMATION_TITLE;
    private javax.swing.JLabel DATE_OF_BIRTH;
    private javax.swing.JFormattedTextField DATE_OF_BIRTH_INPUT;
    private javax.swing.JLabel DD_MM_YYYY;
    private javax.swing.JRadioButton FEMALE_BUTTON;
    private javax.swing.JLabel GENDER;
    private javax.swing.JLabel HOME_ADDRESS_TITLE;
    private javax.swing.JLabel HOME_CITY;
    private javax.swing.JTextField HOME_CITY_INPUT;
    private javax.swing.JLabel HOME_COUNTRY;
    private javax.swing.JComboBox HOME_COUNTRY_INPUT;
    private javax.swing.JLabel HOME_PHONE_NUMBER;
    private javax.swing.JTextField HOME_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel HOME_POSTAL_CODE;
    private javax.swing.JTextField HOME_POSTAL_CODE_INPUT;
    private javax.swing.JLabel HOME_STREET;
    private javax.swing.JTextField HOME_STREET_INPUT;
    private javax.swing.JRadioButton MALE_BUTTON;
    private javax.swing.JLabel MOBILE_PHONE_NUMBER;
    private javax.swing.JTextField MOBILE_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField NAME_INPUT;
    private javax.swing.JCheckBox PAIR_PASSENGER_LUGGAGE;
    private javax.swing.JButton PRINT;
    private javax.swing.JCheckBox PRINT_ON_REGISTER;
    private javax.swing.JButton REGISTER;
    private javax.swing.JLabel SURNAME;
    private javax.swing.JTextField SURNAME_INPUT;
    private javax.swing.JTextField SURNAME_TUSSENVOEGSEL_INPUT;
    private javax.swing.JLabel TEMPORARY_ADDRESS_TITLE;
    private javax.swing.JLabel TEMP_CITY;
    private javax.swing.JTextField TEMP_CITY_INPUT;
    private javax.swing.JLabel TEMP_COUNTRY;
    private javax.swing.JComboBox TEMP_COUNTRY_INPUT;
    private javax.swing.JLabel TEMP_POSTAL_CODE;
    private javax.swing.JTextField TEMP_POSTAL_CODE_INPUT;
    private javax.swing.JLabel TEMP_STREET;
    private javax.swing.JTextField TEMP_STREET_INPUT;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
