/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Date;
import model.Address;

/**
 *
 * @author Haris
 */
public class RegistrationPassenger extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPassenger
     */
    public RegistrationPassenger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        BASIC_INFORMATION_TITLE = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        NAME_INPUT = new javax.swing.JTextField();
        SURNAME = new javax.swing.JLabel();
        SURNAME_TUSSENVOEGSEL_INPUT = new javax.swing.JTextField();
        SURNAME_INPUT = new javax.swing.JTextField();
        DATE_OF_BIRTH = new javax.swing.JLabel();
        DATE_OF_BIRTH_DD_INPUT = new javax.swing.JTextField();
        DATE_OF_BIRTH_MM_INPUT = new javax.swing.JTextField();
        DATE_OF_BIRTH_YYYY_INPUT = new javax.swing.JTextField();
        DD_MM_YYYY = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        MALE_BUTTON = new javax.swing.JRadioButton();
        FEMALE_BUTTON = new javax.swing.JRadioButton();
        HOME_PHONE_NUMBER = new javax.swing.JLabel();
        HOME_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        MOBILE_PHONE_NUMBER = new javax.swing.JLabel();
        MOBILE_PHONE_NUMBER_INPUT = new javax.swing.JTextField();
        HOME_ADDRESS_TITLE = new javax.swing.JLabel();
        HOME_COUNTRY = new javax.swing.JLabel();
        HOME_COUNTRY_INPUT = new javax.swing.JComboBox();
        HOME_CITY = new javax.swing.JLabel();
        HOME_CITY_INPUT = new javax.swing.JTextField();
        HOME_STREET = new javax.swing.JLabel();
        HOME_STREET_INPUT = new javax.swing.JTextField();
        HOME_POSTAL_CODE = new javax.swing.JLabel();
        HOME_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        TEMPORARY_ADDRESS_TITLE = new javax.swing.JLabel();
        TEMP_COUNTRY = new javax.swing.JLabel();
        TEMP_COUNTRY_INPUT = new javax.swing.JComboBox();
        TEMP_CITY = new javax.swing.JLabel();
        TEMP_CITY_INPUT = new javax.swing.JTextField();
        TEMP_STREET = new javax.swing.JLabel();
        TEMP_STREET_INPUT = new javax.swing.JTextField();
        TEMP_POSTAL_CODE = new javax.swing.JLabel();
        TEMP_POSTAL_CODE_INPUT = new javax.swing.JTextField();
        ADDITIONAL_OPTIONS_TITLE = new javax.swing.JLabel();
        PRINT_ON_REGISTER = new javax.swing.JCheckBox();
        PAIR_PASSENGER_LUGGAGE = new javax.swing.JCheckBox();
        PRINT = new javax.swing.JButton();
        REGISTER = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Register Passenger"));

        BASIC_INFORMATION_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BASIC_INFORMATION_TITLE.setText("Basic Information");

        NAME.setText("Name");

        SURNAME.setText("Surname");

        SURNAME_TUSSENVOEGSEL_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SURNAME_TUSSENVOEGSEL_INPUTActionPerformed(evt);
            }
        });

        DATE_OF_BIRTH.setText("Date of Birth");

        DATE_OF_BIRTH_DD_INPUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATE_OF_BIRTH_DD_INPUTActionPerformed(evt);
            }
        });

        DD_MM_YYYY.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        DD_MM_YYYY.setText("(DD_MM_YYYY)");

        GENDER.setText("Gender");

        MALE_BUTTON.setText("Male");
        MALE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALE_BUTTONActionPerformed(evt);
            }
        });

        FEMALE_BUTTON.setText("Female");

        HOME_PHONE_NUMBER.setText("Home Phone Number");

        MOBILE_PHONE_NUMBER.setText("Mobile Phone Number");

        HOME_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HOME_ADDRESS_TITLE.setText("Home Address");

        HOME_COUNTRY.setText("Country");

        HOME_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        HOME_CITY.setText("City");

        HOME_STREET.setText("Street");

        HOME_POSTAL_CODE.setText("Postal Code");

        TEMPORARY_ADDRESS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TEMPORARY_ADDRESS_TITLE.setText("Temporary Address");

        TEMP_COUNTRY.setText("Country");

        TEMP_COUNTRY_INPUT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please select your country ..", "The Netherlands", "Germany", "Belgium" }));

        TEMP_CITY.setText("City");

        TEMP_STREET.setText("Street");

        TEMP_POSTAL_CODE.setText("Postal Code");

        ADDITIONAL_OPTIONS_TITLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ADDITIONAL_OPTIONS_TITLE.setText("Additional Options");

        PRINT_ON_REGISTER.setText("Print on register");

        PAIR_PASSENGER_LUGGAGE.setText("Pair passenger with luggage");

        PRINT.setText("Print");

        REGISTER.setText("Register");
        REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TEMPORARY_ADDRESS_TITLE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NAME)
                                            .addComponent(SURNAME)
                                            .addComponent(DATE_OF_BIRTH)
                                            .addComponent(GENDER)
                                            .addComponent(TEMP_CITY)
                                            .addComponent(TEMP_COUNTRY)
                                            .addComponent(TEMP_STREET)
                                            .addComponent(TEMP_POSTAL_CODE)
                                            .addComponent(HOME_PHONE_NUMBER)
                                            .addComponent(MOBILE_PHONE_NUMBER)
                                            .addComponent(PRINT_ON_REGISTER)
                                            .addComponent(PRINT)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HOME_CITY)
                                            .addComponent(HOME_COUNTRY)
                                            .addComponent(HOME_STREET)
                                            .addComponent(HOME_POSTAL_CODE))))
                                .addGap(43, 43, 43)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PAIR_PASSENGER_LUGGAGE)
                            .addComponent(REGISTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DATE_OF_BIRTH_DD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DATE_OF_BIRTH_MM_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DATE_OF_BIRTH_YYYY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MALE_BUTTON)
                                .addGap(18, 18, 18)
                                .addComponent(FEMALE_BUTTON))))
                    .addComponent(ADDITIONAL_OPTIONS_TITLE)
                    .addComponent(BASIC_INFORMATION_TITLE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DD_MM_YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HOME_ADDRESS_TITLE)
                            .addGap(94, 94, 94)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NAME_INPUT)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(SURNAME_TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SURNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TEMP_POSTAL_CODE_INPUT)
                                .addComponent(TEMP_STREET_INPUT)
                                .addComponent(TEMP_CITY_INPUT)
                                .addComponent(HOME_POSTAL_CODE_INPUT)
                                .addComponent(HOME_STREET_INPUT)
                                .addComponent(HOME_CITY_INPUT)
                                .addComponent(HOME_COUNTRY_INPUT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HOME_PHONE_NUMBER_INPUT)
                                .addComponent(MOBILE_PHONE_NUMBER_INPUT))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(TEMP_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BASIC_INFORMATION_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NAME)
                            .addComponent(NAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SURNAME)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SURNAME_TUSSENVOEGSEL_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SURNAME_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE_OF_BIRTH)
                    .addComponent(DATE_OF_BIRTH_DD_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_BIRTH_MM_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_BIRTH_YYYY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DD_MM_YYYY))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GENDER)
                    .addComponent(MALE_BUTTON)
                    .addComponent(FEMALE_BUTTON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_PHONE_NUMBER)
                    .addComponent(HOME_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MOBILE_PHONE_NUMBER)
                    .addComponent(MOBILE_PHONE_NUMBER_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HOME_ADDRESS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_COUNTRY)
                    .addComponent(HOME_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_CITY)
                    .addComponent(HOME_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HOME_STREET)
                    .addComponent(HOME_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HOME_POSTAL_CODE)
                    .addComponent(HOME_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TEMPORARY_ADDRESS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_COUNTRY)
                    .addComponent(TEMP_COUNTRY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_CITY)
                    .addComponent(TEMP_CITY_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEMP_STREET)
                    .addComponent(TEMP_STREET_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEMP_POSTAL_CODE)
                    .addComponent(TEMP_POSTAL_CODE_INPUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ADDITIONAL_OPTIONS_TITLE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRINT_ON_REGISTER)
                    .addComponent(PAIR_PASSENGER_LUGGAGE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRINT)
                    .addComponent(REGISTER))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MALE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALE_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MALE_BUTTONActionPerformed

    private void DATE_OF_BIRTH_DD_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATE_OF_BIRTH_DD_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATE_OF_BIRTH_DD_INPUTActionPerformed

    private void SURNAME_TUSSENVOEGSEL_INPUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SURNAME_TUSSENVOEGSEL_INPUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SURNAME_TUSSENVOEGSEL_INPUTActionPerformed

    private void REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTERActionPerformed
        
    }//GEN-LAST:event_REGISTERActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDITIONAL_OPTIONS_TITLE;
    private javax.swing.JLabel BASIC_INFORMATION_TITLE;
    private javax.swing.JLabel DATE_OF_BIRTH;
    private javax.swing.JTextField DATE_OF_BIRTH_DD_INPUT;
    private javax.swing.JTextField DATE_OF_BIRTH_MM_INPUT;
    private javax.swing.JTextField DATE_OF_BIRTH_YYYY_INPUT;
    private javax.swing.JLabel DD_MM_YYYY;
    private javax.swing.JRadioButton FEMALE_BUTTON;
    private javax.swing.JLabel GENDER;
    private javax.swing.JLabel HOME_ADDRESS_TITLE;
    private javax.swing.JLabel HOME_CITY;
    private javax.swing.JTextField HOME_CITY_INPUT;
    private javax.swing.JLabel HOME_COUNTRY;
    private javax.swing.JComboBox HOME_COUNTRY_INPUT;
    private javax.swing.JLabel HOME_PHONE_NUMBER;
    private javax.swing.JTextField HOME_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel HOME_POSTAL_CODE;
    private javax.swing.JTextField HOME_POSTAL_CODE_INPUT;
    private javax.swing.JLabel HOME_STREET;
    private javax.swing.JTextField HOME_STREET_INPUT;
    private javax.swing.JRadioButton MALE_BUTTON;
    private javax.swing.JLabel MOBILE_PHONE_NUMBER;
    private javax.swing.JTextField MOBILE_PHONE_NUMBER_INPUT;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField NAME_INPUT;
    private javax.swing.JCheckBox PAIR_PASSENGER_LUGGAGE;
    private javax.swing.JButton PRINT;
    private javax.swing.JCheckBox PRINT_ON_REGISTER;
    private javax.swing.JButton REGISTER;
    private javax.swing.JLabel SURNAME;
    private javax.swing.JTextField SURNAME_INPUT;
    private javax.swing.JTextField SURNAME_TUSSENVOEGSEL_INPUT;
    private javax.swing.JLabel TEMPORARY_ADDRESS_TITLE;
    private javax.swing.JLabel TEMP_CITY;
    private javax.swing.JTextField TEMP_CITY_INPUT;
    private javax.swing.JLabel TEMP_COUNTRY;
    private javax.swing.JComboBox TEMP_COUNTRY_INPUT;
    private javax.swing.JLabel TEMP_POSTAL_CODE;
    private javax.swing.JTextField TEMP_POSTAL_CODE_INPUT;
    private javax.swing.JLabel TEMP_STREET;
    private javax.swing.JTextField TEMP_STREET_INPUT;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
