/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;

/**
 *
 * @author gebak_000
 */
public class SeachBar extends javax.swing.JPanel {

    /**
     * Creates new form SeachBar
     */
    public SeachBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        SEARCH_LABEL = new javax.swing.JLabel();
        PASSENGER_OR_LUGGAGE_SELECTOR = new javax.swing.JComboBox();
        SEARCH_INPUT = new javax.swing.JTextField();
        SEARCH_BUTTON = new javax.swing.JButton();
        ADVANCED_SEARCH_BUTTON = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        LOGOUT_BUTTON = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        SEARCH_LABEL.setText("Search:");
        jToolBar1.add(SEARCH_LABEL);

        PASSENGER_OR_LUGGAGE_SELECTOR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Passenger", "Luggage" }));
        jToolBar1.add(PASSENGER_OR_LUGGAGE_SELECTOR);
        jToolBar1.add(SEARCH_INPUT);

        SEARCH_BUTTON.setText("Search");
        SEARCH_BUTTON.setFocusable(false);
        SEARCH_BUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SEARCH_BUTTON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SEARCH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTONActionPerformed(evt);
            }
        });
        jToolBar1.add(SEARCH_BUTTON);

        ADVANCED_SEARCH_BUTTON.setText("Advanced Search");
        ADVANCED_SEARCH_BUTTON.setFocusable(false);
        ADVANCED_SEARCH_BUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ADVANCED_SEARCH_BUTTON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ADVANCED_SEARCH_BUTTON);
        jToolBar1.add(jSeparator1);

        jLabel2.setText(main.LuggageTrackerTool2.getInstance().getCurrentUser().getUsername() + "[" + main.LuggageTrackerTool2.getInstance().getCurrentUser().getPrivileges() +"]");
        jToolBar1.add(jLabel2);
        jToolBar1.add(jSeparator2);

        LOGOUT_BUTTON.setText("Log out");
        LOGOUT_BUTTON.setFocusable(false);
        LOGOUT_BUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LOGOUT_BUTTON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LOGOUT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUT_BUTTONActionPerformed(evt);
            }
        });
        jToolBar1.add(LOGOUT_BUTTON);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Corendon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(440, 440, 440)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT_BUTTONActionPerformed
        main.LuggageTrackerTool2.getInstance().login();
    }//GEN-LAST:event_LOGOUT_BUTTONActionPerformed

    private void SEARCH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTONActionPerformed
        if("Passenger".equals(PASSENGER_OR_LUGGAGE_SELECTOR.getSelectedItem().toString())) {
            try {
                view.Passenger passengerTab = main.LuggageTrackerTool2.getInstance().getMainMenu().getPassengerTab();
                passengerTab.refreshWithSearch(Integer.parseInt(SEARCH_INPUT.getText()));
                passengerTab.addPassengerItemsToTable();
                main.LuggageTrackerTool2.getInstance().getMainMenu().getjTabbedPane().setSelectedIndex(0);
                SEARCH_INPUT.setText("");
            } catch (SQLException ex) {
                System.err.println("Passenger search not found");
            }
        }
        if("Luggage".equals(PASSENGER_OR_LUGGAGE_SELECTOR.getSelectedItem().toString())) {
            try {
                view.Luggage luggageTab = main.LuggageTrackerTool2.getInstance().getMainMenu().getLuggageTab();
                luggageTab.refreshWithSearch(Integer.parseInt(SEARCH_INPUT.getText()));
                luggageTab.addLuggageItemsToTable();
                main.LuggageTrackerTool2.getInstance().getMainMenu().getjTabbedPane().setSelectedIndex(1);
                SEARCH_INPUT.setText("");
            } catch (SQLException ex) {
                System.err.println("Luggage search not found");
            }
        }
        
    }//GEN-LAST:event_SEARCH_BUTTONActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADVANCED_SEARCH_BUTTON;
    private javax.swing.JButton LOGOUT_BUTTON;
    private javax.swing.JComboBox PASSENGER_OR_LUGGAGE_SELECTOR;
    private javax.swing.JButton SEARCH_BUTTON;
    private javax.swing.JTextField SEARCH_INPUT;
    private javax.swing.JLabel SEARCH_LABEL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
