/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.BorderLayout;

/**
 *
 * @author reintjehard
 */
public class SideBar extends javax.swing.JPanel {

    /**
     * Creates new form SideBar
     */
    private RegistrationPassenger regPassengerControl;
    private RegistrationLuggage regLuggageControl;
    
    public SideBar() {
        initComponents();
        setLayout(new BorderLayout(10, 10));
        this.regPassengerControl = new view.RegistrationPassenger();
        this.regLuggageControl = new view.RegistrationLuggage();
        add(this.regPassengerControl, BorderLayout.NORTH);
        add(this.regLuggageControl, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the regPassengerControl
     */
    public RegistrationPassenger getRegPassengerControl() {
        return regPassengerControl;
    }

    /**
     * @param regPassengerControl the regPassengerControl to set
     */
    public void setRegPassengerControl(RegistrationPassenger regPassengerControl) {
        this.regPassengerControl = regPassengerControl;
    }

    /**
     * @return the regLuggageControl
     */
    public RegistrationLuggage getRegLuggageControl() {
        return regLuggageControl;
    }

    /**
     * @param regLuggageControl the regLuggageControl to set
     */
    public void setRegLuggageControl(RegistrationLuggage regLuggageControl) {
        this.regLuggageControl = regLuggageControl;
    }
}
